version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: my_postgres_db
    environment:
      POSTGRES_DB: planovac_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: